### ISSUE TITLE
Duplication of human disease

### ISSUE THREAD

**Issue by rwilson-ebi** [mpi2/aws-mpi2#32]
The human diseases associated with a gene should be grouped to show unique entries.

For an example see the BICRA gene page
https://nginx.mousephenotype-dev.org/genes/MGI:2154263
https://www.mousephenotype.org/data/genes/MGI:2154263

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1RVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c65fa1f1cb4e7f974c80a1ffff365ef9cb811975/image.png" alt="image.png" />

<img width="1436" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2ZVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f056fa083278652bb89ee628c7d8950dc5e1e77e/image.png" alt="image.png" />

**Comment by ficolo** [comment]
The current website preserves only the disease association with the maximum similarity score per disease term.
