### ISSUE TITLE
[Gene Images] Add isSpecialFormat boolean flag to the Domain Object

### ISSUE THREAD

**Issue by ficolo** [mpi2/aws-mpi2#33]
Example JSON File: [part-00395-e67749f8-a353-485c-b8cb-c257c7ec13f4-c000.json](https://github.com/mpi2/aws-mpi2/files/14587988/part-00395-e67749f8-a353-485c-b8cb-c257c7ec13f4-c000.json)

**Comment by ogunes-ebi** [comment]
isSpecialFormat is added
